[BUGS#1228] chore: workaround innosetup docker permission issue
- Support containerd/nerdctl

Signed-off-by: Hiroshi Miura <miurahr@linux.com>

diff --git a/ci/iscc b/ci/iscc
--- a/ci/iscc
+++ b/ci/iscc
@@ -14,16 +14,21 @@ bindpaths() {
 
 if type nerdctl &> /dev/null ; then
     CMD=nerdctl
-    IMAGE=amake/innosetup:innosetup6-buster
 elif type docker &> /dev/null ; then
     CMD=docker
+else
+  echo Please install docker or nerdctl!
+  exit 2
+fi
 
-    # workaround for build failure on CI env.
-    # see https://sourceforge.net/p/omegat/bugs/1228/
-    PUID=`id -u`
-    PGID=`id -g`
-    IMAGE=omegatorg/innosetup:innosetup6
-    cat << __EOF__ | docker build -t $IMAGE - || true
+# workaround for build failure on CI env.
+# see https://sourceforge.net/p/omegat/bugs/1228/
+PUID=`id -u`
+PGID=`id -g`
+IMAGE=omegatorg/innosetup:innosetup6
+CONTEXT=`mktemp -d`
+
+cat << __EOF__  > /$CONTEXT/Dockerfile
 FROM docker.io/amake/innosetup:innosetup6-buster
 USER root
 RUN usermod -u $PUID -o xclient && groupmod -g $PGID -o xusers
@@ -36,12 +41,7 @@ WORKDIR /work
 ENTRYPOINT ["iscc"]
 __EOF__
 
-else
-  echo Please install docker or nerdctl!
-  exit 2
-fi
-
-umask a+w
+$CMD build -t $IMAGE $CONTEXT
 exec $CMD run -i --rm  \
    -u `id -u`:`id -g` \
    -v "$PWD":/work \
