chore: backport container tasks improvements (#914)
- Update build.gradle to check also nerdctl
- Update docgen/iscc shell scripts

Signed-off-by: Hiroshi Miura <miurahr@linux.com>

diff --git a/ci/iscc b/ci/iscc
--- a/ci/iscc
+++ b/ci/iscc
@@ -12,5 +12,37 @@ bindpaths() {
     done
 }
 
-umask a+w
-exec docker run --rm -i -v "$PWD":/work $(bindpaths "$@") amake/innosetup:innosetup6 $(relpaths "$@")
+# workaround for build failure on CI env.
+# see https://sourceforge.net/p/omegat/bugs/1228/
+PUID=`id -u`
+PGID=`id -g`
+IMAGE=omegatorg/innosetup:innosetup6
+CONTEXT=`mktemp -d`
+
+cat << __EOF__  > $CONTEXT/Dockerfile
+FROM docker.io/amake/innosetup:innosetup6-buster
+USER root
+RUN usermod -u $PUID -o xclient && groupmod -g $PGID -o xusers
+RUN chown -R $PUID:$PGID /home/xclient /work
+USER xclient
+ENV HOME /home/xclient
+ENV WINEPREFIX /home/xclient/.wine
+ENV WINEARCH win32
+WORKDIR /work
+ENTRYPOINT ["iscc"]
+__EOF__
+
+CMD="$(type -p docker)" || [[ -e $CMD ]] && $CMD info >/dev/null 2>1 || CMD="$(type -p nerdctl)"
+echo select container CLI: $CMD
+$CMD info || false
+
+if ! $CMD build -t $IMAGE $CONTEXT ; then
+  echo Container build error for ISCC, abort...
+  exit 1
+fi
+exec $CMD run -i --rm  \
+   -u `id -u`:`id -g` \
+   -v "$PWD":/work \
+   $(bindpaths "$@") \
+   $IMAGE \
+   $(relpaths "$@")
